apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nfs-rbac.yaml
  - storageclass.yaml
  - nfs-client-provisioner.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - service.yaml
  - service-headless.yaml
