apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../deploy/manifests

namespace: default
nameSuffix: -hyperspace
commonLabels:
  app: kubebot
  chain: hyperspace

images:
  - name: viewfintest/kubebot
  - name: viewfintest/hyperspace
  - name: viewfintest/node-liveness-probe
  - name: viewfintest/snapshot-init-container:v1

configMapGenerator:
  - name: kubebot
    files:
      - kubebot.yaml
