apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../deploy/manifests

namespace: default
nameSuffix: -hyperspace
commonLabels:
  app: kubebot
  chain: hyperspace

images:
  - name: viewfintest/kubebot
    newTag: v0.3.0
  - name: viewfintest/hyperspace
    newTag: v0.10.0
  - name: viewfintest/node-liveness-probe
    newTag: v0.5.1
  - name: viewfintest/snapshot-init-container
    newTag: v0.1.0

configMapGenerator:
  - name: kubebot
    files:
      - kubebot.yaml
